{{ if .Values.aws.key.create }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "accumulation-zone.awsSecretName" . }}"
  labels:
    {{- include "accumulation-zone.labels" . | nindent 4 }}
data:
  KEY_ID: "{{ .Values.aws.key.id}}"
  KEY_SECRET: "{{ .Values.aws.key.secret}}"
{{ end }}
